# Generated by Django 3.2.9 on 2024-07-31 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_remove_wishlist_buy_now'),
        ('warranty', '0002_warranty_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='cart.order'),
        ),
    ]
